remote: origin
helm-extra-args: --timeout 600s
check-version-increment: true
validate-yaml: true
validate-chart-schema: true
validate-maintainers: true
target-branch: main

chart-dirs:
  - charts

chart-repos:
  - elastic=https://helm.elastic.co
  - jetstack=https://charts.jetstack.io
  - bitnami=https://charts.bitnami.com/bitnami
