apiVersion: v2
name: mozilla-common-voice
icon: https://voice.mozilla.org/dist/f01895c77138837851f87c2e40acbd58.svg
version: 0.4.1
description: Deploy Mozilla Common Voice web application
type: application
keywords:
  - Mozilla
  - common-voice
  - voice
  - deepspeech
home: https://voice.mozilla.org
sources:
  - https://github.com/mozilla/voice-web
maintainers:
  - name: Alberto del Barrio
    email: alberto@mozilla.com
dependencies:
- name: mysql
  version: 1.6.4
  condition: mysql.enabled
  repository: https://kubernetes-charts.storage.googleapis.com

- name: redis
  version: ~10.4.1
  condition: redis.enabled
  repository: https://kubernetes-charts.storage.googleapis.com
