namespace: voice-dev

# Parameters for voice-web container 
voice_web:
  hpa:
    enabled: false
    max_replicas: 6
    min_replicas: 2

  replicas: 3 # Required if "hpa_enabled =  false"

  requests:
    cpu: 500m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1024Mi

  config:
    new_relic_enabled: "false"

redis:
  enabled: true

elasticsearch:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi

kibana:
  enabled: true
