# Parameters for voice-web container
voice_web:
  use_default_secrets_file: true
  use_external_secrets: false
  deployment_name: voice
  service_account_name: voice-dev
  ingress:
    enabled: false
    class: voice-dev
    host: voice.mozilla.org
    additional_host: voice.mozilla.com
  hpa:
    enabled: false
    max_replicas: 6
    min_replicas: 2

  replicas: 1   # Required if "hpa_enabled =  false"

  requests:
    cpu: 500m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1024Mi

  image: "itsre/voice-web:master-latest"

  service_account:
    annotations: {}

  extra_containers: []

  extra_volumes: []

  config:
    environment: "default"
    new_relic_enabled: "false"
    server_port: 9000
    prod: "false"
    version: "test"
    mysql:
      root_user: "root"
      user: "voice"
      db_name: "voice"
      port: \"3306\"
      host: "localhost"
    s3:
      bucket_name: "common-voice-bucket"
      location: "us-west-2"
    admin_emails: "[admin@organization.com]"
    redis_url: "redis://voice-dev-redis-master.voice-dev.svc.cluster.local/"
    kibana:
      url: "http://voice-dev-kibana.voice-dev.svc.cluster.local:5601/"
      prefix: "/app/kibana"
      admins: "[admin@organization.com]"
    last_dataset: "default"

  es_sync:
    enabled: false

  # This are default non-production base64'd values
  secrets:
    mysql:
      root_pw: "ZGVmYXVsdC1ub24tc2VjdXJlLXJvb3QtcGFzc3dvcmQ="
      user_pw: "ZGVmYXVsdC1ub24tc2VjdXJlLXBhc3N3b3Jk"
      host: "bXlzcWwtdm9pY2U="
    app_secret: "bXktdG9wLXNlY3JldC1zZWNyZXQK"
    auth0:
      domain: "YXV0aC5hdXRoMC5jb20K"
      client_id: "ZmFrZS1jbGllbnQtaWQK"
      client_secret: "ZmFrZS1jbGllbnQtc2VjcmV0Cg=="
    basket_api_key: "MDEyMzQ1Njc4OQo="

new_relic:
  enabled: false
  app_name: voice

dependecies:
  - name: mysql
    version: 1.6.4
    condition: mysql.enabled
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: redis
    version: ~10.4.1
    condition: redis.enabled
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: elasticsearch
    version: ~7.6.0
    condition: elasticsearch.enabled
    repository: https://helm.elastic.co
  - name: kibana
    version: ~7.6.0
    condition: kibana.enabled
    repository: https://helm.elastic.co

mysql:
  enabled: true
  fullnameOverride: mysql-voice
  mysqlUser: voice
  mysqlDatabase: voice
  mysqlPassword: default-non-secure-password
  mysqlRootPassword: default-non-secure-root-password
  imageTag: 5.7.14

redis:
  enabled: false

elasticsearch:
  enabled: false
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi

kibana:
  enabled: false
