apiVersion: v2
name: sentence-collector
description: A Helm chart for Common Voice's Sentence Collector
type: application
version: 0.1.0
keywords:
  - Mozilla
  - common-voice
  - voice
  - sentence-collector
home: https://commonvoice.mozilla.org/sentence-collector
sources:
  - https://github.com/Common-Voice/sentence-collector
maintainers:
  - name: Alberto del Barrio
    email: alberto@mozilla.com

dependencies:
- name: mysql
  version: 1.6.4
  condition: mysql.enabled
  repository: https://kubernetes-charts.storage.googleapis.com
