apiVersion: v2
name: sentence-collector
description: Deploy Common Voice's Sentence Collector
type: application
version: 1.0.2
keywords:
  - Mozilla
  - common-voice
  - voice
  - sentence-collector
home: https://commonvoice.mozilla.org/sentence-collector
sources:
  - https://github.com/Common-Voice/sentence-collector
maintainers:
  - name: jzinner
    email: jenc@mozillafoundation.org
  - name: JZ
    email: jenny@mozillafoundation.org
dependencies:  # used only in CI testing
- name: mysql
  version: 8.4.2
  condition: mysql.enabled
  repository: https://charts.bitnami.com/bitnami
