{{- if .Values.externalSecret.create -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "sentence-collector.fullname" . }}
spec:
  backendType: secretsManager
  dataFrom:
  - /sentence-collector/{{ .Values.environment }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentence-collector.fullname" . }}
data:
  # echo -n "mysql://sc:defaultpassword@mysql:3306/sc" | base64
  SC_CONNECT: bXlzcWw6Ly9zYzpkZWZhdWx0cGFzc3dvcmRAbXlzcWwuY2hhcnQtY2ktZTJlOjMzMDYvc2M=
{{- end }}
