---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice
  namespace: {{ .Values.namespace}}
spec:
  selector:
    matchLabels:
      app: voice
  {{ if eq .Values.voice_web.hpa.enabled false }}
  replicas: {{ .Values.voice_web.replicas }}
  {{ end }}
  template:
    metadata:
      labels:
        app: voice
    spec:
      containers:
      - name: web
        command:
          - yarn
          - start:prod
        image: {{ .Values.voice_web.image }}
        ports:
        - containerPort: 9000
        livenessProbe:
          httpGet:
            port: 9000
            path: /api/v1/metrics
          periodSeconds: 10
          initialDelaySeconds: 60
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1
        resources:
          limits:
            cpu: {{ .Values.voice_web.limits.cpu }}
            memory: {{ .Values.voice_web.limits.memory }}
          requests:
            cpu: {{ .Values.voice_web.requests.cpu }}
            memory: {{ .Values.voice_web.requests.memory }}
        envFrom:
        - configMapRef:
            name: voice-config
        {{ if eq .Values.voice_web.use_secrets_file true }}
        - secretRef:
            name: voice-secrets
        {{ end }}
