{{ if eq .Values.voice_web.hpa.enabled true }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: voice
spec:
  maxReplicas: {{ .Values.voice_web.hpa.max_replicas }}
  minReplicas: {{ .Values.voice_web.hpa.min_replicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: voice
  targetCPUUtilizationPercentage: 80
{{ end }}
