{{ if eq .Values.voice_web.ingress.enabled true }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: voice-ingress
  namespace: {{ .Values.namespace}}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.voice_web.ingress.class }}
{{- if .Values.voice_web.ingress.extra_annotations }}
      {{- toYaml .Values.voice_web.ingress.extra_annotations | nindent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.voice_web.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: voice
          servicePort: 9000
{{- if .Values.voice_web.ingress.additional_host }}
  - host: {{ .Values.voice_web.ingress.additional_host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: voice
          servicePort: 9000

{{- end }}
{{ end }}

