{{ if eq .Values.voice_web.ingress.enabled true }}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: voice-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.voice_web.ingress.class }}
{{- if .Values.voice_web.ingress.extra_annotations }}
      {{- toYaml .Values.voice_web.ingress.extra_annotations | nindent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.voice_web.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: voice
          servicePort: 9000
  {{- end }}
{{ end }}

