apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
  annotations:
  {{- if .Values.voice_web.service_account.annotations }}
  {{ toYaml .Values.voice_web.service_account.annotations | indent 4 }}
  {{- end }}
